### ISSUE TITLE
Username and Password Panel

### ISSUE THREAD

**Issue by Victorhlab** [jyberg/Nextion-Qwery#1]
I have created a Username and Password implementation. This is specifically for a bigger screen, the 4.3" device. I would like to create a feature branch for you that I can commit this work.

I would also like to do some styling updates to it.

Would you be willing to grant me access to this repo so that I can extend your work?

**Comment by jyberg** [comment]
Access granted, please updade also readme.md, so that others can also found new bigger screen option. Also please include additionat picture and possible Inkscape etc. files so that fure modification are eastier. Maybe we should also add version information and change history...

Also it is nice to hear that this project has also help others... ;)
